#FROM python:3.10-slim
FROM python:latest

USER root
# Installer dépendances système
# RUN apt-get update && apt-get install -y gcc git && apt-get clean
#RUN apt-get update && apt-get install -y --no-install-recommends build-essential git && rm -rf /var/lib/apt/lists/*
# Empêcher les warnings de dépôt Debian "trixie/testing"
RUN apt-get update --allow-releaseinfo-change && \
    apt-get install -y --no-install-recommends gcc git && \
    rm -rf /var/lib/apt/lists/*

# Installer dbt-core + dbt-bigquery (dernière version publiée)
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir "dbt-core" "dbt-bigquery"

WORKDIR /usr/app/dbt

CMD ["bash"]
